theme: jekyll-theme-minimal
title: Shanna Davidson
description: Advanced Scientific Visual Communications Spring 2018
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Hello, Shanna
    url: setup
  - title: PZA Uptake
    url: pza
  - title: Isoniazid Uptake
    url: niz
